Many improvements in scripts
Signed-off-by: Haris Gušić <harisgusic.dev@gmail.com>

diff --git a/.local/bin/rb b/.local/bin/rb
--- a/.local/bin/rb
+++ b/.local/bin/rb
@@ -1,9 +1,12 @@
 #!/bin/bash
 # One-time reboot into selected OS
 
-set -e
+set -e # Quit if any command fails
 
-index="$(grep "menuentry '\|submenu '" /boot/grub/grub.cfg | grep -v -P '\t'  | grep -i -n "$1" | head -1 | awk -F':' '{print $1}')"
+index="$(grep "menuentry '\|submenu '" /boot/grub/grub.cfg |\
+  grep -v -P '\t' |\
+  grep -i -n "$1" |\
+  head -1 | awk -F':' '{print $1}')"
 if [ -z $index ]; then
   echo "No entry found"
 else 
@@ -11,7 +14,7 @@ else
   echo "Selected menuentry: $index. Proceed?"
   read response
   if [ "$response" == 'y' ]; then
-    sudo grub-reboot $index
+    sudo grub-reboot $index >/home/haris/src/grublog 2>&1
     reboot
   fi
 fi
